config/routes.rb
Smilingatconfusion::Application.routes.draw do

  root to: "tabs#index"

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get "/signin", to: "sessions#new"
  post "/signin", to: "sessions#create"

  resources :tabs do
    resources :comments
  end
  resources :artists
  resources :tunings
  resources :albums
  resources :comments
  resources :users
  resources :posts

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :tabs
  validates_presence_of :name
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  def index
    @artists = Artist.all
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.new(artist_params)
    respond_to do |format|
      format.html do
        if @artist.save
          flash[:notice] = "Artist has been created."
          redirect_to @artist
        else
          flash[:alert] = "Artist has not been created."
          render action: "new"
        end
      end
      format.js do
        render text: @artist.errors.full_messages.join,
          status: :unprocessable_entity unless @artist.save
      end
    end
  end

  def show
  end

  def edit
  end

  def update
    if @artist.update(artist_params)
      flash[:notice] = "Artist has been updated."
      redirect_to @artist
    else
      flash[:alert] = "Artist has not been updated."
      render action: "edit"
    end
  end

  def destroy
    @artist.destroy

    flash[:notice] = "Artist has been destroyed."

    redirect_to artists_path
  end

  private

  def artist_params
    params.require(:artist).permit(:name)
  end

  def set_artist
    @artist = Artist.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "The artist you were looking for could not be found."
    redirect_to artists_path
  end

end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_form.html.erb
<div class="new_form_div" id="new_artist_form_div">
  <%= link_to "", class: 'close-div' do %>
    <i class="icon-remove"></i>
  <% end %>
  <%= simple_form_for @artist, remote: true, id: :new_artist do |f| %>
    <%= f.input :name %>
    <%= f.button :submit %>
  <% end %>
</div>

app/views/artists/create.js.erb
$('#new_artist_form_div').remove();
$('#add_artist_link').show();
$('#tab_artist_id').append('<option value="<%= @artist.id %>"><%= @artist.name %></option>')
$('#tab_artist_id').val('<%= @artist.id %>')

app/views/artists/edit.html.erb
<h2>Edit Artist</h2>
<%= render "form" %>

app/views/artists/index.html.erb
<ul>
<% @artists.each do |artist| %>
  <li><%= link_to artist.name, artist %>
      <%= link_to("Edit", edit_artist_path(artist)) %>
      <%= link_to "Delete", artist_path(artist),
            method: :delete,
            data: { confirm: "Are you sure you want to delete this artist?"
                  } %>
  </li>
<% end %>
</ul>
<br>
<%= link_to "New Artist", new_artist_path %>

app/views/artists/new.html.erb
<h2>New Artist</h2>
<%= render "form" %>

app/views/artists/new.js.erb
$('#add_artist_link').hide().parent("form").after('<%= j render("form") %>')
$('#add_artist_link').click(
  $('#new_artist_form_div').show()
    .css($('#tab_artist_id').offset())
)

app/views/artists/show.html.erb
<h2><%= @artist.name %></h2>
<ul>
<% @artist.tabs.each do |tab| %>
    <li>
      <%= link_to tab.title, tab %>
    </li>
<% end %>
</ul>