config/routes.rb
Smilingatconfusion::Application.routes.draw do

  root to: "tabs#index"

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get "/signin", to: "sessions#new"
  post "/signin", to: "sessions#create"

  resources :tabs do
    resources :comments
  end
  resources :artists
  resources :tunings
  resources :albums
  resources :comments
  resources :users
  resources :posts

end

app/models/user.rb
class User < ActiveRecord::Base
  include TheRoleUserModel
  has_many :tabs
  def self.from_omniauth(auth)
    where(auth.slice("provider", "uid")).first || create_from_omniauth(auth)
  end

  def self.create_from_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["nickname"]
      user.avatar = auth["info"]["image"]
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = "You have signed up successfully."
      redirect_to @user
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "User has been updated."
      redirect_to @user
    else
      flash[:alert] = "User has not been updated."
      render action: "edit"
    end
  end

private

  def set_user
      @user = User.find(params[:id])
  rescue ActiveRecord::RecordNotFound
      flash[:alert] = "The user profile you were looking for could not be found."
      redirect_to tabs_path
  end

  def user_params
    params.require(:user).permit(:name,
                                 :email,
                                 :password,
                                 :password_confirmation)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= simple_form_for @user do |f| %>
  <%= f.input :name, label: "Username" %>
  <%= f.input :email %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>
  <%= f.button :submit, params[:action] == "new" ? "Sign Up" : nil %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit User</h1>
<%= render "form" %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= render "form" %>

app/views/users/show.html.erb
<img class="img-rounded" src=<%= @user.avatar %> />
<%= @user.name %>
Role: <%= @user.role if @user.role %>
<br/>
<%= link_to "Edit", edit_user_path %>