config/routes.rb
Smilingatconfusion::Application.routes.draw do

  root to: "tabs#index"

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get "/signin", to: "sessions#new"
  post "/signin", to: "sessions#create"

  resources :tabs do
    resources :comments
  end
  resources :artists
  resources :tunings
  resources :albums
  resources :comments
  resources :users
  resources :posts

end

app/models/tab.rb
class Tab < ActiveRecord::Base
  acts_as_commentable
  belongs_to :album
  belongs_to :artist
  belongs_to :tuning
  belongs_to :user
  validates :title, presence: true, uniqueness: true
  validates_presence_of :body, :artist, :tuning
end

app/controllers/tabs_controller.rb
  class TabsController < ApplicationController
  before_action :login_required, except: [:show, :index]
  before_action :role_required,  except: [:show, :index]

  before_action :set_tab, only: [:show, :edit, :update, :destroy]
  before_action :owner_required, only: [:edit, :update, :destroy]

  def index
    @tabs = Tab.all
  end

  def new
    @tab = Tab.new
  end

  def create
    @tab = Tab.new(tab_params)
    @tab.user = current_user

    if @tab.save
      flash[:notice] = "Tab has been created."
      redirect_to @tab
    else
      flash[:alert] = "Tab has not been created."
      render action: "new"
    end
  end

  def show
    @comment = @tab.comments.new
    @comments = @tab.comments.load
  end

  def edit
  end

  def update
    @tab.user = current_user
    if @tab.update(tab_params)
      flash[:notice] = "Tab has been updated."
      redirect_to @tab
    else
      flash[:alert] = "Tab has not been updated."
      render action: "edit"
    end
  end

  def destroy
    @tab.destroy

    flash[:notice] = "Tab has been destroyed."

    redirect_to tabs_path
  end

  private

    def tab_params
      params.require(:tab).permit(:title, :artist_id, :album_id, :tuning_id, :notes, :body)
    end

    def set_tab
      @tab = Tab.find(params[:id])
      @owner_check_object = @tab
    rescue ActiveRecord::RecordNotFound
      flash[:alert] = "The tab you were looking for could not be found."
      redirect_to tabs_path
    end

end

app/helpers/tabs_helper.rb
module TabsHelper
end

app/views/tabs/_form.html.erb
<%= simple_form_for @tab do |f| %>
  <%= f.input :title %>
  <%= f.association :artist, include_blank: false %>
  <%= link_to new_artist_path, remote: true, class: "btn btn-info",id: :add_artist_link do%>
    <i class="icon-plus"></i>
  <% end %>
  <br />
  <br />
  *<%= f.association :album %>
  <%= link_to new_album_path, remote: true, class: "btn btn-info",id: :add_album_link do%>
    <i class="icon-plus"></i>
  <% end %>
  <br />
  <br />
  <%= f.association :tuning, label_method: :display, include_blank:false%>
  <%= link_to new_tuning_path, remote: true, class: "btn btn-info",id: :add_tuning_link do%>
    <i class="icon-plus"></i>
  <% end %>
  <br />
  <br />
  <%= f.input :notes, input_html: { class: 'wide_text_area' } %>
  <%= f.input :body, input_html: { class: 'tab_body wide_text_area', rows: 50 } %>
  <%= f.button :submit, class: 'btn-primary' %>
<% end %>

app/views/tabs/edit.html.erb
<h2>Edit Tab</h2>
<%= render "form" %>

app/views/tabs/index.html.erb
<table class='table table-striped'>
  <thead>
    <tr>
      <th>Song Title</th>
      <th>Artist</th>
      <th>Album</th>
      <th>Tuning</th>
      <th>Last Updated By</th>
      <th>Last Updated On</th>
    </tr>
  </thead>
  <tbody>
    <% @tabs.each do |tab| %>
      <tr>
        <td><%= link_to tab.title, tab %></td>
        <td><%= link_to tab.artist.name, tab.artist %></td>
        <td><%= tab.album.name if tab.album %></td>
        <td><%= tab.tuning.notes %></td>
        <td><%= tab.user.name %></td>
        <td><%= tab.updated_at.strftime("%B %d %I:%M %p") %></td>
        <% if current_user %>
          <td>
            <% if current_user.has_role?(:tabs, :edit) %>
              <%= link_to(edit_tab_path(tab), class: 'btn btn-mini') do %>
                  <i class="icon-edit"></i>
              <% end %>
            <% end %>
            <% if current_user.has_role?(:tabs, :delete) %>
              <%= link_to tab_path(tab),
                  method: :delete,
                  data: { confirm: "Are you sure you want to delete this tab?"
                        }, class: 'btn btn-danger btn-mini'  do %>
                <i class="icon-remove"></i>
              <% end %>
            <% end %>
          </td>
        <% end %>
      </tr>
    <% end %>

  </tbody>
</table>

<% if current_user && current_user.has_role?(:tabs, :new) %>
  <%= link_to "New Tab", new_tab_path, class: 'btn btn-primary' %>
<% end %>

app/views/tabs/new.html.erb
<h2>New Tab</h2>
<%= simple_form_for @tab do |f| %>
  <%= f.input :title %>
  <%= f.input :notes %>
  <%= f.input :body %>
  <%= f.button :submit %>
<% end %>

app/views/tabs/show.html.erb
<h2><%= @tab.title %></h2>
<h3><%= @tab.artist.name %></h3>
<span id='submitter'>Last update by <%= @tab.user.name %></span>
<p>Album: <%= @tab.album.name if @tab.album %></p>
<p><%= @tab.tuning.display %></p>
<p><%= @tab.notes %></p>
<span class="tab_body"><%= @tab.body %></span>

<div class="comments">
  <h4>Comments</h4>

  <table class="table table-striped">
    <% @comments.each do |comment| %>
      <% next if comment.comment == nil %>
      <tr>
        <td> <%= comment.comment %></td>
        <td> <%=comment.user.name if comment.user %> </td>
        <td> <%=comment.created_at.strftime("%B %d %I:%M %p") if comment.created_at %></td>
        <% if current_user && (current_user.has_role?(:comments, :destroy) || comment.user == current_user) %>
          <td>
          <%= link_to [@tab, comment],
              method: :delete,
              data: { confirm: "Are you sure you want to delete this comment?"
                    }, class: 'btn btn-danger btn-mini'  do %>
            <i class="icon-remove"></i>
          <% end %>
        </td>
        <% end %>
      </tr>
    <% end %>
  </table>
</div>

<% if current_user && current_user.has_role?(:comments, :new) %>
  <%= simple_form_for [@tab, @comment] do |f| %>
    <%= f.input :comment, input_html: { rows: 5, class: 'wide_text_area' }%>
    <%= f.button :submit, "Add Comment", class: 'btn-primary' %>
  <% end %>
<% end %>