config/routes.rb
Smilingatconfusion::Application.routes.draw do

  root to: "tabs#index"

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get "/signin", to: "sessions#new"
  post "/signin", to: "sessions#create"

  resources :tabs do
    resources :comments
  end
  resources :artists
  resources :tunings
  resources :albums
  resources :comments
  resources :users
  resources :posts

end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Smiling at Confusion", root_path, :class => 'brand' %>
<ul class="nav pull-left">
  <li <% if controller.controller_name == "tabs" && controller.action_name == "index" %>
    class="active" <% end %>>
    <%= link_to('Tabs', tabs_path) %>
  </li>
</ul>
<ul class="nav pull-right">
  <% if current_user %>
    <% if current_user.admin? %>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          Admin
          <b class="caret"></b>
        </a>
        <ul class ="dropdown-menu">
          <li>
            <%= link_to "Roles", admin_roles_path %>
          </li>
        </ul>
    <% end %>
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
      <img src="<%= current_user.avatar %>" class="img-rounded resize"/>
      <%= current_user.name %>
        <b class="caret"></b>
      </a>
      <ul class="dropdown-menu">
        <li>
          <%= link_to "Sign out", signout_path %>
        </li>
      </ul>
    </li>
  <% else %>
    <li>
      <%= link_to "Sign in with Twitter", "/auth/twitter" %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Smiling at Confusion</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="navbar navbar-fixed-top">
    <nav class="navbar-inner">
      <div class="container">
        <%= render 'layouts/navigation' %>
      </div>
    </nav>
  </header>
  <div id="main" role="main">
    <div class="container">
      <div class="content">
       <div class="row">
        <div class="span12">
          <div class="well">
            <%= render 'layouts/messages' %>

            <%= yield :role_sidebar %>
            <%= yield :role_main %>
            <%= yield %>

          </div>
        </div>
      </div>
      <footer>
      </footer>
    </div>
  </div>

</body>
</html>